---
- name: Install Catalogue
  hosts: catalogue
  become: true
  tasks:
  - name: Enable module nodejs
    ansible.builtin.shell: dnf module enable nodejs:20 -y
  - name: Install nodejs:20
    ansible.builtin.dnf:
      name: nodejs
      state: present
  - name: Add user roboshop
    ansible.builtin.user:
      name: roboshop
      home: /app
      system: true
      shell: /sbin/nologin
      comment: "roboshop system user"
  - name: Delete Directory /app
    ansible.builtin.file:
      path: /app
      state: absent
  - name: Create directory /app
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Delete downloaded catalogue zip file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent
  - name: Download package from url
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
  - name: Unarchive the catalogue zip folder
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: npm download dependencies
    community.general.npm:
      path: /app
      state: present
  - name: Copy Catalog Service file
    ansible.builtin.template:
      src: catalogue.service
      dest: /etc/systemd/system/
  - name: Reload systemd daemon
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: Enable and Start Catalogue Service
    ansible.builtin.service:
      name: catalogue
      enabled: true
      state: started
  - name: Copy MongoDB repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/
  - name: Install MongoDB-client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present
  - name: check databases index
    ansible.builtin.command: mongosh --host {{ MONGODB_HOST }} --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: debug catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: Add Master Data in monogdb
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: ( catalogue_output.stdout | int ) < 0
